### ISSUE TITLE
[Unity 2021.3.6f1] cannot convert from 'string' to 'System.Collections.Generic.List<UnityEngine.Networking.IMultipartFormSection>'

### ISSUE THREAD

**Issue by Maxime66410** [keijiro/ScriptGeneratorTest#13]
# Unity version 2021.3.6f1

# Error

`Assets\Editor\OpenAIUtil.cs(28,28): error CS1503: Argument 2: cannot convert from 'string' to 'System.Collections.Generic.List<UnityEngine.Networking.IMultipartFormSection>'`

`Assets\Editor\OpenAIUtil.cs(28,59): error CS1503: Argument 3: cannot convert from 'string' to 'byte[]'`

I know i do use version Unity 2022.2, but i test just with another version.

**Comment by keijiro** [comment]
Those errors are caused by the old API. As noted on README, this project requires 2022.2 that provides the new API.

**Comment by keijiro** [comment]
I close this issue as "won't fix". Please reopen it if it still reproduces after upgrading to 2022.2.

**Comment by Nanobrainiac** [comment]
Thanks for the answer @keijiro
